// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab-client/graphql.go

// Package mock_gitlab is a generated GoMock package.
package mock_gitlab

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// MockGraphQLInterface is a mock of GraphQLInterface interface.
type MockGraphQLInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGraphQLInterfaceMockRecorder
}

// MockGraphQLInterfaceMockRecorder is the mock recorder for MockGraphQLInterface.
type MockGraphQLInterfaceMockRecorder struct {
	mock *MockGraphQLInterface
}

// NewMockGraphQLInterface creates a new mock instance.
func NewMockGraphQLInterface(ctrl *gomock.Controller) *MockGraphQLInterface {
	mock := &MockGraphQLInterface{ctrl: ctrl}
	mock.recorder = &MockGraphQLInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphQLInterface) EXPECT() *MockGraphQLInterfaceMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockGraphQLInterface) Do(query gitlab.GraphQLQuery, response any, options ...gitlab.RequestOptionFunc) (*gitlab.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query, response}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(*gitlab.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGraphQLInterfaceMockRecorder) Do(query, response interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query, response}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGraphQLInterface)(nil).Do), varargs...)
}
