// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gitlab/repo.go

// Package mock_gitlab is a generated GoMock package.
package mock_gitlab

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	git "github.com/hbk619/gh-peruse/internal/git"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Base mocks base method.
func (m *MockRepo) Base(remoteName string) (*git.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base", remoteName)
	ret0, _ := ret[0].(*git.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Base indicates an expected call of Base.
func (mr *MockRepoMockRecorder) Base(remoteName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base", reflect.TypeOf((*MockRepo)(nil).Base), remoteName)
}
